### ISSUE TITLE
Unable to run specs after fork

### ISSUE THREAD

**Issue by ekampp** [drewish/rspec-rails-swagger#39]
Hey there.

When forking the project I'm unable to run the specs because: 

```
LoadError:
  cannot load such file -- [...]/rspec-rails-swagger/spec/testapp/config/environment
# ./spec/rails_helper.rb:3:in `require'
# ./spec/rails_helper.rb:3:in `<top (required)>'
# ./spec/swagger_helper.rb:2:in `require'
# ./spec/swagger_helper.rb:2:in `<top (required)>'
# ./spec/requests/request_spec.rb:1:in `require'
# ./spec/requests/request_spec.rb:1:in `<top (required)>'
```

Is there some step that I'm missing. I have looked in the README, and there doesn't seem to be any mention about any special steps to run the specs for the project it self.

Thanks,

Emil

**Comment by ekampp** [comment]
Hmm.. it was in the contribution doc. Never mind.
